# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Train and Build restuarant reviews model

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build_train_nlp_knn_model:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        cd restaurant_reviews/knn_model
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build and train the NLP model
      run: |
        cd restaurant_reviews/knn_model
        python text_classifier_knn.py
    - name: Validate the NLP model
      run: |
        cd restaurant_reviews/knn_model
        python -m pytest validation.py
