# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Train and Build the model

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  checks:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox
    - name: Run lint, stylechecks, typechecks
      run: |
        cd titanic
        tox 

  train:

    runs-on: ubuntu-latest
    needs: [checks]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox
    - name: Train the model
      run: |
        cd titanic
        tox -e train
        
  build:

    runs-on: ubuntu-latest
    needs: [train]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Build the model
      run: |
        cd titanic
        pip install build
        python -m build
    - name: Publish packages
      uses: actions/upload-artifact@v3.1.0
      with:
        name: model-whl
        path: titanic/dist/*.whl
        if-no-files-found: error
